export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';

// export const FETCH_BLOG_DETAILS = 'FETCH_BLOG_DETAILS';
// export const CHANGE_PAGINATE = 'CHANGE_PAGINATE';